// Generated by pnpm --filter @harbor/protocol generate:harbor-abi.
// Source: contracts/out/HarborRedeemer.sol/HarborRedeemer.json
import type { Abi } from "./types.js";

export const harborRedeemerArtifactContractName = "HarborRedeemer" as const;
export const harborRedeemerArtifactPath =
  "contracts/out/HarborRedeemer.sol/HarborRedeemer.json" as const;

export const harborRedeemerAbi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "assetManagerOrRegistry",
        type: "address",
        internalType: "address",
      },
      {
        name: "resolveAssetManagerFromRegistry",
        type: "bool",
        internalType: "bool",
      },
      {
        name: "initialDefaultKeeperExecutor",
        type: "address",
        internalType: "address",
      },
      {
        name: "initialOwner",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "receive",
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "FXRP_ASSET_MANAGER_REGISTRY_NAME",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "string",
        internalType: "string",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "assetDecimals",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint8",
        internalType: "uint8",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "assetManagerAddress",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "defaultKeeperExecutor",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "executeDefault",
    inputs: [
      {
        name: "proof",
        type: "tuple",
        internalType: "struct IReferencedPaymentNonexistence.Proof",
        components: [
          {
            name: "merkleProof",
            type: "bytes32[]",
            internalType: "bytes32[]",
          },
          {
            name: "data",
            type: "tuple",
            internalType: "struct IReferencedPaymentNonexistence.Response",
            components: [
              {
                name: "attestationType",
                type: "bytes32",
                internalType: "bytes32",
              },
              {
                name: "sourceId",
                type: "bytes32",
                internalType: "bytes32",
              },
              {
                name: "votingRound",
                type: "uint64",
                internalType: "uint64",
              },
              {
                name: "lowestUsedTimestamp",
                type: "uint64",
                internalType: "uint64",
              },
              {
                name: "requestBody",
                type: "tuple",
                internalType:
                  "struct IReferencedPaymentNonexistence.RequestBody",
                components: [
                  {
                    name: "minimalBlockNumber",
                    type: "uint64",
                    internalType: "uint64",
                  },
                  {
                    name: "deadlineBlockNumber",
                    type: "uint64",
                    internalType: "uint64",
                  },
                  {
                    name: "deadlineTimestamp",
                    type: "uint64",
                    internalType: "uint64",
                  },
                  {
                    name: "destinationAddressHash",
                    type: "bytes32",
                    internalType: "bytes32",
                  },
                  {
                    name: "amount",
                    type: "uint256",
                    internalType: "uint256",
                  },
                  {
                    name: "standardPaymentReference",
                    type: "bytes32",
                    internalType: "bytes32",
                  },
                  {
                    name: "checkSourceAddresses",
                    type: "bool",
                    internalType: "bool",
                  },
                  {
                    name: "sourceAddressesRoot",
                    type: "bytes32",
                    internalType: "bytes32",
                  },
                ],
              },
              {
                name: "responseBody",
                type: "tuple",
                internalType:
                  "struct IReferencedPaymentNonexistence.ResponseBody",
                components: [
                  {
                    name: "minimalBlockTimestamp",
                    type: "uint64",
                    internalType: "uint64",
                  },
                  {
                    name: "firstOverflowBlockNumber",
                    type: "uint64",
                    internalType: "uint64",
                  },
                  {
                    name: "firstOverflowBlockTimestamp",
                    type: "uint64",
                    internalType: "uint64",
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        name: "redemptionRequestId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "executeXrpDefault",
    inputs: [
      {
        name: "proof",
        type: "tuple",
        internalType: "struct IXRPPaymentNonexistence.Proof",
        components: [
          {
            name: "merkleProof",
            type: "bytes32[]",
            internalType: "bytes32[]",
          },
          {
            name: "data",
            type: "tuple",
            internalType: "struct IXRPPaymentNonexistence.Response",
            components: [
              {
                name: "attestationType",
                type: "bytes32",
                internalType: "bytes32",
              },
              {
                name: "sourceId",
                type: "bytes32",
                internalType: "bytes32",
              },
              {
                name: "votingRound",
                type: "uint64",
                internalType: "uint64",
              },
              {
                name: "lowestUsedTimestamp",
                type: "uint64",
                internalType: "uint64",
              },
              {
                name: "requestBody",
                type: "tuple",
                internalType: "struct IXRPPaymentNonexistence.RequestBody",
                components: [
                  {
                    name: "minimalBlockNumber",
                    type: "uint64",
                    internalType: "uint64",
                  },
                  {
                    name: "deadlineBlockNumber",
                    type: "uint64",
                    internalType: "uint64",
                  },
                  {
                    name: "deadlineTimestamp",
                    type: "uint64",
                    internalType: "uint64",
                  },
                  {
                    name: "destinationAddressHash",
                    type: "bytes32",
                    internalType: "bytes32",
                  },
                  {
                    name: "amount",
                    type: "uint256",
                    internalType: "uint256",
                  },
                  {
                    name: "checkFirstMemoData",
                    type: "bool",
                    internalType: "bool",
                  },
                  {
                    name: "firstMemoDataHash",
                    type: "bytes32",
                    internalType: "bytes32",
                  },
                  {
                    name: "checkDestinationTag",
                    type: "bool",
                    internalType: "bool",
                  },
                  {
                    name: "destinationTag",
                    type: "uint256",
                    internalType: "uint256",
                  },
                  {
                    name: "proofOwner",
                    type: "address",
                    internalType: "address",
                  },
                ],
              },
              {
                name: "responseBody",
                type: "tuple",
                internalType: "struct IXRPPaymentNonexistence.ResponseBody",
                components: [
                  {
                    name: "minimalBlockTimestamp",
                    type: "uint64",
                    internalType: "uint64",
                  },
                  {
                    name: "firstOverflowBlockNumber",
                    type: "uint64",
                    internalType: "uint64",
                  },
                  {
                    name: "firstOverflowBlockTimestamp",
                    type: "uint64",
                    internalType: "uint64",
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        name: "redemptionRequestId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "fAssetTokenAddress",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lotSizeUBA",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setDefaultKeeperExecutor",
    inputs: [
      {
        name: "executor",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [
      {
        name: "newOwner",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "DefaultKeeperExecutorUpdated",
    inputs: [
      {
        name: "executor",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RedemptionDefaultForwarded",
    inputs: [
      {
        name: "caller",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "redemptionRequestId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "forwardedExecutorFeeNatWei",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "AssetManagerResolutionFailed",
    inputs: [],
  },
  {
    type: "error",
    name: "DirectNativeTransferRejected",
    inputs: [],
  },
  {
    type: "error",
    name: "NativeForwardFailed",
    inputs: [],
  },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [
      {
        name: "owner",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "ReentrancyGuardReentrantCall",
    inputs: [],
  },
  {
    type: "error",
    name: "ZeroAddress",
    inputs: [],
  },
] as const satisfies Abi;
